name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: actions/checkout@v3
        run: |
          npm install 
          npm test
